import type { Restaurant } from '../types'

export const SEONGSU_RESTAURANTS: readonly Restaurant[] = [
  {
    id: 'jiuguan',
    name: '지우관',
    category: 'chinese',
    description: '홍콩식 딤섬 & 대만요리 전문점',
    address: '서울 성동구 뚝섬로9길 16',
    phone: '0507-1309-1103',
    hours: '화~토 11:30~21:00 (브레이크 15:00~17:00), 월/일 휴무',
    distanceFromStation: '도보 7분',
    priceRange: '1~2만원',
    availableModes: ['dine-in'],
    tags: ['중식', '딤섬', '홍콩요리'],
  },
  {
    id: 'hyojadong',
    name: '효자동목고기',
    category: 'korean',
    description: '제육, 부대찌개 등 고기 전문',
    address: '서울 성동구 연무장5가길 25 SKV1타워 101호',
    phone: '0507-1381-0402',
    hours: '평일 10:00~22:00 (브레이크 15:00~17:00), 주말 17:00~22:00',
    distanceFromStation: '도보 4분',
    priceRange: '1~2만원',
    availableModes: ['dine-in'],
    tags: ['고기', '제육', '부대찌개'],
  },
  {
    id: 'otokimbap',
    name: '오토김밥',
    category: 'snack',
    description: '김밥, 닭강정',
    address: '서울 성동구 성수이로14길 14 가동 1층',
    phone: '0507-1362-0652',
    hours: '평일 10:00~20:00, 주말 10:00~19:00',
    distanceFromStation: '도보 5분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in', 'delivery'],
    tags: ['김밥', '닭강정', '혼밥', '가성비'],
  },
  {
    id: 'ukon-curry',
    name: '우콘카레',
    category: 'japanese',
    description: '일본 정통 가정식 카레 전문점',
    address: '서울 성동구 성수이로10길 8',
    phone: '070-4124-8769',
    hours: '매일 11:00~21:30, 일요일 휴무',
    distanceFromStation: '도보 5분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['카레', '일식', '혼밥'],
  },
  {
    id: 'yesterday-curry',
    name: '어제의카레',
    category: 'japanese',
    description: '스프카레 전문점',
    address: '서울 성동구 성수동2가 (경수중학교 방향 골목)',
    phone: '0507-1416-0833',
    hours: '평일 11:30~21:00 (브레이크 15:00~16:00), 토 12:00~21:00, 일 휴무',
    note: '골목 안쪽, 내비 필수',
    distanceFromStation: '도보 8분',
    priceRange: '1~2만원',
    availableModes: ['dine-in'],
    tags: ['카레', '스프카레'],
  },
  {
    id: 'jeongdeun',
    name: '정든식당',
    category: 'korean',
    description: '보쌈정식, 국수',
    address: '서울 성동구 연무장15길 11 C동 2층 202호',
    phone: '0507-1495-0831',
    hours: '평일 11:00~22:00 (브레이크 14:30~17:00), 주말 12:00~22:00',
    note: '직원할인 10%',
    distanceFromStation: '도보 4분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['보쌈', '국수', '가성비'],
  },
  {
    id: 'wak-burger',
    name: '왁버거',
    category: 'western',
    description: '정통 미국식 수제버거, 매일 100% 소고기 패티 블렌딩',
    address: '서울 성동구 아차산로 132 성수드림빌드 1층 101호',
    hours: '매일 10:30~22:00',
    distanceFromStation: '도보 6분',
    priceRange: '1~2만원',
    availableModes: ['dine-in', 'delivery'],
    tags: ['햄버거', '수제버거'],
  },
  {
    id: 'katsu-workshop',
    name: '카츠공방',
    category: 'japanese',
    description: '규동, 돈까스, 마제소바 등 일식',
    address: '성수동 (정확한 위치 네이버지도 확인)',
    note: '소규모 매장',
    distanceFromStation: '-',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['규동', '돈까스', '혼밥'],
  },
  {
    id: 'songtan-budae',
    name: '송탄진대광부대찌개',
    category: 'korean',
    description: '송탄식 부대찌개 전문',
    address: '서울 성동구 아차산로 97, 201호',
    phone: '0507-1495-5159',
    hours: '매일 11:00~22:00 (L.O. 20:30)',
    distanceFromStation: '도보 5분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['부대찌개', '단체'],
  },
  {
    id: 'ibukjip',
    name: '이북집순대',
    category: 'korean',
    description: '찹쌀순대, 국밥 전문',
    address: '서울 성동구 성수이로20길 10',
    phone: '02-464-2270',
    hours: '평일 09:30~21:30 (브레이크 15:30~16:30), 주말 09:00~20:00',
    distanceFromStation: '도보 6분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['순대', '국밥', '혼밥'],
  },
  {
    id: 'geumgeum',
    name: '금금',
    category: 'korean',
    description: '퓨전한식, 보리된장 고기 국수',
    address: '서울 성동구 성수이로12길 11',
    phone: '0507-1418-4477',
    hours: '매일 11:00~21:00 (평일 브레이크 15:00~17:00, L.O. 20:20)',
    distanceFromStation: '도보 10분',
    priceRange: '1~2만원',
    availableModes: ['dine-in'],
    tags: ['비빔밥', '퓨전한식'],
  },
  {
    id: 'ekki-udon',
    name: '에끼우동',
    category: 'japanese',
    description: '냉우동 전문',
    address: '서울 성동구 성수동2가 275-96',
    phone: '0507-1358-7534',
    hours: '11:00~22:00',
    distanceFromStation: '도보 5분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['우동', '냉우동', '혼밥'],
  },
  {
    id: 'cuco',
    name: '쿠코',
    category: 'western',
    description: '유럽풍 파스타 & 브런치 카페',
    address: '서울 성동구 아차산로11길 12, 진일빌딩 1층',
    hours: '11:00~22:00, 화요일 휴무',
    distanceFromStation: '도보 5분',
    priceRange: '1~2만원',
    availableModes: ['dine-in'],
    tags: ['파스타', '브런치'],
  },
  {
    id: 'seongsusok',
    name: '성수속 향연',
    category: 'chinese',
    description: '신라호텔 출신 셰프의 건강한 중식',
    address: '서울 성동구 성수이로 65, 협성빌딩 102호',
    phone: '02-463-0753',
    hours: '매일 11:00~21:00',
    distanceFromStation: '도보 4분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['중식', '짜장면', '짬뽕'],
  },
  {
    id: 'udon-kinoya',
    name: '우동키노야 성수점',
    category: 'japanese',
    description: '수제 우동 전문 체인',
    address: '서울 성동구 성수이로12길 13, 1층',
    phone: '0507-1403-2182',
    hours: '매일 11:00~21:00 (L.O. 20:20)',
    distanceFromStation: '도보 8분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['우동', '혼밥'],
  },
  {
    id: 'oatt',
    name: '오트 성수',
    category: 'cafe',
    description: '유럽풍 브런치 카페, 워크인 전용',
    address: '서울 성동구 성수이로18길 31, 풍림테크원 1층 101호',
    phone: '070-8834-0815',
    hours: '월~금/일 09:00~19:00, 토 09:00~20:00',
    note: '비싸다',
    distanceFromStation: '도보 10분',
    priceRange: '2~3만원',
    availableModes: ['dine-in'],
    tags: ['브런치', '카페', '데이트'],
  },
  {
    id: 'matdeun',
    name: '맛든',
    category: 'korean',
    description: '정갈한 한식 반상 전문',
    address: '서울 성동구 아차산로11길 11, 108호',
    phone: '02-3409-0999',
    hours: '평일 11:30~20:00 (브레이크 15:00~17:30), 토 11:30~15:00, 일 휴무',
    distanceFromStation: '도보 3분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['한식', '반상', '혼밥'],
  },
  {
    id: 'haengun',
    name: '행운식당',
    category: 'japanese',
    description: '바삭 두툼 왕돈가스, 2006년부터 운영',
    address: '서울 성동구 아차산로11길 11, 동성빌딩',
    phone: '02-497-8818',
    hours: '월~금 10:30~19:30 (브레이크 15:30~17:00)',
    distanceFromStation: '도보 3분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['돈가스', '혼밥', '가성비'],
  },
  {
    id: 'woongkal',
    name: '웅칼 성수',
    category: 'korean',
    description: '닭다리살 칼국수 전문',
    address: '서울 성동구 아차산로 92, 광명타워 1층 105호',
    hours: '캐치테이블 예약 가능',
    note: '가성비 있고 괜찮은 칼국수',
    distanceFromStation: '도보 4분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['칼국수', '가성비', '혼밥'],
  },
  {
    id: 'gazoku',
    name: '가조쿠',
    category: 'japanese',
    description: '소바/우동 전문 (소바 매장 & 우동 매장 별도)',
    address: '서울 성동구 연무장길 31-2, 1층',
    phone: '0507-1434-2177',
    hours: '매일 11:00~20:00 (브레이크 14:30~17:00)',
    distanceFromStation: '도보 5분',
    priceRange: '1~2만원',
    availableModes: ['dine-in'],
    tags: ['소바', '우동', '일식'],
  },
  {
    id: 'tendong',
    name: '텐동식당',
    category: 'japanese',
    description: '바삭 텐동 전문, 기본텐동 9,000원',
    address: '서울 성동구 연무장5가길 20-1, 1층',
    phone: '02-6339-0309',
    hours: '매일 11:00~21:00 (브레이크 15:00~17:00)',
    distanceFromStation: '도보 3분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['텐동', '튀김', '혼밥', '가성비'],
  },
  {
    id: 'pizza-slice',
    name: '피자슬라이스',
    category: 'western',
    description: '도쿄발 뉴욕 스타일 조각 피자',
    address: '서울 성동구 아차산로 159, 지하1층',
    hours: '매일 11:00~20:00 (L.O. 19:30)',
    distanceFromStation: '도보 7분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['피자', '조각피자'],
  },
  {
    id: 'paper-plate',
    name: '페이퍼플레이트',
    category: 'western',
    description: '뉴욕 스타일 조각 피자',
    address: '서울 성동구 성수이로14길 15, 1층',
    hours: '매일 11:30~21:00, 월요일 휴무',
    distanceFromStation: '도보 6분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['피자', '조각피자'],
  },
  {
    id: 'musinsa-food',
    name: '무신사 푸드코트',
    category: 'etc',
    description: '무신사 메가스토어 4층 푸드가든',
    address: '서울 성동구 성수이로 62, 무신사 메가스토어 4층',
    phone: '0507-1355-0606',
    hours: '매일 11:00~21:00 (L.O. 20:30)',
    distanceFromStation: '도보 8분',
    priceRange: '1만원 이하',
    availableModes: ['dine-in'],
    tags: ['분식', '피자', '쌀국수', '푸드코트'],
  },
  {
    id: 'marionae',
    name: '마리오네',
    category: 'western',
    description: '나폴리 피자 & 파스타, 이용시간 90분',
    address: '서울 성동구 광나루로2길 23-1',
    phone: '0507-1381-6779',
    hours: '11:30~20:00 (브레이크 15:00~17:00), 월/화 휴무',
    note: '인기 맛집, 웨이팅 필수',
    distanceFromStation: '도보 10분',
    priceRange: '2~3만원',
    availableModes: ['dine-in'],
    tags: ['피자', '파스타', '나폴리'],
  },
  {
    id: 'solsot',
    name: '솥솥 성수점',
    category: 'korean',
    description: '연어/전복/스테이크 등 다양한 솥밥',
    address: '서울 성동구 연무장5가길 24, 1층',
    phone: '010-2046-1130',
    hours: '매일 11:30~21:00 (평일 브레이크 15:00~17:00)',
    note: '웨이팅 있음',
    distanceFromStation: '도보 3분',
    priceRange: '1.5~2.6만원',
    availableModes: ['dine-in'],
    tags: ['솥밥', '데이트'],
  },
  {
    id: 'seongsu-jjigae',
    name: '성수찌개',
    category: 'korean',
    description: '스팸찌개, 돼지김치찌개 반반세트+고기추가가 국룰. 솥밥도 맛있었음',
    address: '성수동',
    closed: true,
    note: '폐업',
    distanceFromStation: '-',
    priceRange: '-',
    availableModes: ['dine-in'],
    tags: ['찌개', '솥밥'],
  },
] as const
